[package]
name = "narp"
description = "Daemon integrating arpwatch and nmap functionality"
authors = ["Cameron Cooper"]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/Cameron-Cooper22/narp"
repository = "https://github.com/Cameron-Cooper22/narp"
readme = "README.md"
keywords = ["arp", "nmap", "network", "scan", "security"]

[dependencies]
daemonize = "0.5.0"

# Network
dns-lookup = "2.0.4"
ipnetwork = "0.20.0"
pnet = "0.35.0"
pnet_datalink = "0.35.0"

# Writing to database
sqlite = "0.36.1"
