[package]
name = "narp"
description = "Daemon integrating arpwatch and nmap functionality"
authors = ["Cameron Cooper"]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/Cameron-Cooper22/narp"
repository = "https://github.com/Cameron-Cooper22/narp"
readme = "README.md"
keywords = ["arp", "nmap", "network", "scan", "security"]

[dependencies]
bit-set = "0.8.0"
bit-vec = "0.8.0"
bitvec = "1.0.1"
byteorder = "1.5.0"
daemonize = "0.5.0"

# Network
dns-lookup = "2.0.4"
etherparse = "0.16.0"
icmp = "0.3.0"
ipnetwork = "0.20.0"
local-ip-address = "0.6.3"
nix = "0.29.0"
pnet = "0.35.0"
pnet_datalink = "0.35.0"
rand = "0.8.5"
serde = "1.0.210"
socket2 = "0.5.7"

# Writing to database
sqlite = "0.36.1"
syslog = "7.0.0"
thiserror = "1.0.64"
threadpool = "1.8.1"
tun-tap = "0.1.4"

